sudo: required
service:
  - docker

before_install:
  - docker build -t gmkrtchyan/docker-react -f Dockerfile.dev .

script:
  - docker run gmkrtchyan/docker-react npm run test -- --help #--coverage fucking coverage turned to be not exiting as was intended, turning to --help for travis ci to pass the build

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-914659533361"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secret: "$AWS_SECRET_KEY"